# Generated by Django 4.2.15 on 2024-09-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_category_quiz_description_quiz_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='number_of_questions',
        ),
        migrations.AddField(
            model_name='theme',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
